### ISSUE TITLE
map not working if kernel does not return key-value

### ISSUE THREAD

**Issue by mdrocco** [alpha-unito/PiCo#16]
problem resides in compiling the optimized farm (map + reduce-by-key) regardless the kernel type

**Comment by droccom** [comment]
closing since analogous to #18

**Comment by mdrocco** [comment]
The problem is quite substantial here: FF terms for the optimized pipelines (e.g., map + reduce-by-key) are always compiled, regardless data types, and the compilation is triggered by the upstream node (e.g., map).

I do not have any immediate solution so far, I propose either:
- to turn off optimizations;
- a workaround: triggering the compilation from the downstream node (e.g., reduce-by-key), so that the compilation is not triggered if data types do not allow it.

@cmisale @FalkenRambaldi Please vote!

**Comment by ARMartinelli** [comment]
I prefer the latter

**Comment by cmisale** [comment]
Same thing as #18?
_______________________________
Claudia Misale, PhD
Research Staff Member
Cognitive and Cloud, Data-Centric Solutions
IBM T.J. Watson Research Center
Yorktown Heights, NY
 
E-mail: c.misale@ibm.com
Phone: +1 (914) 945-1693  
 
 
----- Original message -----From: Maurizio Drocco <notifications@github.com>To: alpha-unito/PiCo <PiCo@noreply.github.com>Cc: Claudia Misale <c.misale@ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [alpha-unito/PiCo] map not working if kernel does not return key-value (#16)Date: Tue, Jan 30, 2018 5:07 AM 
The problem is quite substantial here: FF terms for the optimized pipelines (e.g., map + reduce-by-key) are always compiled, regardless data types, and the compilation is triggered by the upstream node (e.g., map).
I do not any immediate solution so far, I propose either:
        to turn off optimizations;        a workaround: triggering the compilation from the downstream node (e.g., reduce-by-key), so that the compilation is not triggered if data types do not allow it.
@cmisale @FalkenRambaldi Please vote!

**Comment by cmisale** [comment]
second

**Comment by cmisale** [comment]
I vote (again) for the second

**Comment by mdrocco** [comment]
I prefer the former but we are under democracy, I will try with the latter.

**Comment by mdrocco** [comment]
Triggering the compilation of map + reduce-by-key from the downstream node is not possible in the current implementation: reduce-by-key does not know the input type of map.

Unless you have some idea, I will turn off the optimizations by now.

**Comment by mdrocco** [comment]
Fixed in #43.
