### ISSUE TITLE
wrong reduce-by-key interface

### ISSUE THREAD

**Issue by mdrocco** [alpha-unito/PiCo#18]
Signature should be:

```c++
template<typename K, typename V>
class ReduceByKey(std::function<V(V &, V &)>);
````
 @cmisale @FalkenRambaldi do you agree?

(related to #16)

**Comment by droccom** [comment]
The problem is quite substantial here: FF terms for the optimized pipelines (e.g., map + reduce-by-key) are always compiled, regardless data types, and the compilation is triggered by the upstream node (e.g., map).

I do not any immediate solution so far, I propose either:
- to turn off optimizations;
- a workaround: triggering the compilation from the downstream node (e.g., reduce-by-key), so that the compilation is not triggered if data types do not allow it.

@cmisale @FalkenRambaldi Please vote!

**Comment by cmisale** [comment]
I vote for the second option, turning all off would be a performance disaster for some pipelines
 
_______________________________
Claudia Misale, PhD
Research Staff Member
Cognitive and Cloud, Data-Centric Solutions
IBM T.J. Watson Research Center
Yorktown Heights, NY
 
E-mail: c.misale@ibm.com
Phone: +1 (914) 945-1693  
 
 
----- Original message -----From: Maurizio Drocco <notifications@github.com>To: alpha-unito/PiCo <PiCo@noreply.github.com>Cc: Claudia Misale <c.misale@ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [alpha-unito/PiCo] wrong reduce-by-key interface (#18)Date: Tue, Jan 30, 2018 5:06 AM 
The problem is quite substantial here: FF terms for the optimized pipelines (e.g., map + reduce-by-key) are always compiled, regardless data types, and the compilation is triggered by the upstream node (e.g., map).
I do not any immediate solution so far, I propose either:
        to turn off optimizations;        a workaround: triggering the compilation from the downstream node (e.g., reduce-by-key), so that the compilation is not triggered if data types do not allow it.
@cmisale @FalkenRambaldi Please vote!

**Comment by cmisale** [comment]
why K?

**Comment by mdrocco** [comment]
This is the signature of the class, K is used within the body (e.g., passed when instantiating the FF node)

**Comment by cmisale** [comment]
I don't understand why the input type is K in the template and V in the constructor

**Comment by cmisale** [comment]
I propose 
template<KV>
class ReduceByKey(std::function<V(V &, V &)>);

I prefer template <KV> because it would be easier to "match" the datatype with the operator right before the ReduceByKey. I think it goes better with the flow of data types.
What do you think?
Of course please point out all the problems I don't see.
@droccom @FalkenRambaldi

**Comment by cmisale** [comment]
I don't know what I did, but the thing was supposed to be the following:
```
template <typename KV> 
class ReduceByKey(std::function<V(V &, V &)>);
```

**Comment by mdrocco** [comment]
I agree, let me try this way.
